# Generated by Django 5.1.7 on 2025-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importado', models.BooleanField(default=False)),
                ('ncm', models.CharField(max_length=10, verbose_name='NCM')),
                ('produto', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('estoque', models.IntegerField(verbose_name='estoque atual')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='estoque minimo')),
            ],
            options={
                'ordering': ('produto',),
            },
        ),
    ]
